### ISSUE TITLE
未被正常处理的issue和pr

### ISSUE THREAD

**Issue by fangrongxaing** [sibbay-ai/operating#112]
由于一些特殊原因，导致未被正常处理的issue和pr ，其中的issue和pr已经完成，当是操作不当导致未被登记。
它们分别是
h5宣传设计
https://github.com/sibbay-ai/operating/issues/98
对应pr
https://github.com/sibbay-ai/operating/pull/99

漫画设计1
https://github.com/sibbay-ai/operating/issues/106
对应pr
https://github.com/sibbay-ai/operating/pull/107

地球日画设计
https://github.com/sibbay-ai/operating/issues/96
对应pr
https://github.com/sibbay-ai/operating/pull/97

@fushang318

**Comment by fushang318** [comment]
在 https://github.com/sibbay-ai/operating/pull/109 用挂单的方式帮你处理了
