### ISSUE TITLE
经期演示视频review

### ISSUE THREAD

**Issue by skytian1** [sibbay-ai/operating#117]
背景https://github.com/sibbay-ai/cooperation-issues/issues/719

主要工作：审核演示内容，看是否将文案设计全部实现。

**Comment by skytian1** [comment]
申请开发 deadline:2018-06-05 size:0.1 @fushang318

**Comment by skytian1** [comment]
没有经期前一周的文案视频。经期文案中，12号和13号文案是相同的，正常应该是变化的。 @bqx619

**Comment by bqx619** [comment]
@skytian1 昨晚就回复了, 您看一下
![image](https://user-images.githubusercontent.com/9692149/40670055-082a2664-639b-11e8-88bd-243d214ec09d.png)
