### ISSUE TITLE
新年“测体重”活动策划

### ISSUE THREAD

**Issue by alisahuxu** [sibbay-ai/operating#12]
https://shimo.im/docs/mEaGMDGC3pIKVsnU

**Comment by georgeliuyu** [comment]
建议如下：
1、能带入小程序的使用（互动脚本可以根据开发）
2、H5、公众号是否能协同
3、是否能社交
4、奖励的标准需要不可预知，但可尽快反馈。
你可以参考一下“蠢鸽子”理论。

**Comment by alisahuxu** [comment]
https://shimo.im/docs/C3hcSoxpvToN89k9
活动重新修改了以下。 @georgeliuyu

**Comment by georgeliuyu** [comment]
@alisahuxu 
可将“福犬”的1和2创意都融合到第三中：
谁是最美体重波动曲线的福犬？
最美春节体重曲线
。。。

这次我们就把一个核心做好。

**Comment by georgeliuyu** [comment]
@alisahuxu 建议你组织一次头脑风暴。

**Comment by alisahuxu** [comment]
好的。收到~

**Comment by alisahuxu** [comment]
目前，小白健康新年策划如下：

小胖子过新年，添福不添肉
一、宣传
1.宣传第一波
漫画：《小胖子的新年心事》
内容：新年期间，小胖子有很多做不了的事情，都成了他的心事——买不到可以炫耀的新衣服、没办法磕头领红包、没有勇气吃红烧肉

2.宣传第二波
文章：《体重秤不会告诉你的秘密》
内容：如何正确的称量体重

3.宣传第三波
文章：《全民参与——帮助小胖子新年减肥成功》
内容：活动正式规则：如何参与记录体重，获得奖励等

4.宣传第四波
文章：《开奖啦》
内容：活动结束后，公布获奖用户，公布小胖子是否减肥成功。

二、活动
1.活动时间：过年七天（2018年2月15日——2018年2月21日）
2.活动主题：小胖子过新年，添福不添肉
3.活动目的：让更多的用户知道小白健康，并参与本次活动
4.活动规则：
（1）用户参与活动，记录每天体重
（2）T+1日统计T日的体重：n位用户体重增加（或减少）记录为+Xn（或-Xn)，±Xn将会增加到小胖子的身上，形成T+1日小胖子的状态。
（3）活动最后一天，最接近小胖子体重增加（或减少）数值的用户，将会神秘大奖一份。
（4）用户必须保证每天参与记录，才能符合（3）的参与条件。


三、需要支持的工作
宣传
（1）漫画《小胖子的新年心事》
（2）文章《体重秤不会告诉你的秘密》

UI
（1）小胖子变瘦或变胖的几个状态
（2）记录体重的页面
（3）展示T+1日所有用户体重数值的状态
（4）用户中断记录提醒的页面
  (6)  中奖公告页面

产品/技术
（1）用户记录体重上传数据，显示结果


刘总：我知道目前技术正在全力保证正式上线的工作，我希望他们能预估一下这个活动工期，活动最迟2月12日就应该上线。
@georgeliuyu @fangrongxaing

**Comment by georgeliuyu** [comment]
@alisahuxu 今天晚上你说说年会的事宜

**Comment by alisahuxu** [comment]
@georgeliuyu 11小时

**Comment by alisahuxu** [comment]
@fazhen @fushang318 :内容如上。

**Comment by alisahuxu** [comment]
@lixinxuan这里有活动宣传方案。
