### ISSUE TITLE
例假互动状态迁移位置文案

### ISSUE THREAD

**Issue by skytian1** [sibbay-ai/operating#121]
来源：https://github.com/sibbay-ai/cooperation-issues/issues/719
内容：
         完成状态迁移位置的互动文案
    @fushang318 @bqx619

**Comment by skytian1** [comment]
申请开发 deadline:2018-06-04  size:0.2 @fushang318

**Comment by skytian1** [comment]
https://shimo.im/docs/vj33iSVY6ikp9tJp @fushang318 @bqx619 请review是否可以？

**Comment by fushang318** [comment]
由  @bqx619  review 即可

**Comment by bqx619** [comment]
@skytian1 

1. 询问的间隔最好给我一个, 从用户接受的角度给一个粗略的方案
1. 同种类型问题不是只询问一次, 所以是否多套方案

**Comment by skytian1** [comment]
https://shimo.im/docs/vj33iSVY6ikp9tJp @bqx619 请帮忙review是否OK？

**Comment by fushang318** [comment]
变更 deadline:2018-06-08
