### ISSUE TITLE
开始界面设计稿

### ISSUE THREAD

**Issue by fangrongxaing** [sibbay-ai/operating#128]
@georgeliuyu  @fushang318 
工作被设计小白界面的图片
工作内容：微信的开机有个地球上的小人，小白开机的时候也需要一个页面。制作这个创意页面

**Comment by fangrongxaing** [comment]
申请开发 deadline:2018-08-15 size:2.5 @fushang318

**Comment by fushang318** [comment]
@fangrongxaing 工作内容没看懂

**Comment by fushang318** [comment]
补充一下工作内容的介绍吧，然后提交PR即可  @fangrongxaing
