### ISSUE TITLE
视频第一稿制作

### ISSUE THREAD

**Issue by fangrongxaing** [sibbay-ai/operating#131]
视频的初步视频稿制作，工作内容，组织gif并制作视频 @fazhen

**Comment by fangrongxaing** [comment]
@fazhen 
申请开发 deadline:2018-08-15

**Comment by fazhen** [comment]
李飞，小荣制作的功能介绍视频已经验收，我在此仓库中无权限打标签，请你来协助打标签并合并 @fushang318

**Comment by fushang318** [comment]
@fangrongxaing @fazhen 提交物是一个图片？
