### ISSUE TITLE
封面图设计

### ISSUE THREAD

**Issue by alisahuxu** [sibbay-ai/operating#14]
请根据以下标题，设计两张图，尺寸和上次一样

1.儿童冬季常见病小宝典
2.高血压科普

@fangrongxaing 

争取下周一之前给到我。谢谢~

**Comment by fangrongxaing** [comment]
补发 @georgeliuyu 
![ok1](https://user-images.githubusercontent.com/33997808/35095222-a7cfd752-fc82-11e7-9aec-12fac458fe1a.png)
![ok2](https://user-images.githubusercontent.com/33997808/35095223-a8057d30-fc82-11e7-9fb2-a160807e499d.png)
