### ISSUE TITLE
请制作“大寒”节气的闪图

### ISSUE THREAD

**Issue by alisahuxu** [sibbay-ai/operating#15]
如题，可沟通，1月20日是大寒（周六）。 @fangrongxaing

**Comment by fangrongxaing** [comment]
收到 @alisahuxu

**Comment by fangrongxaing** [comment]
![5](https://user-images.githubusercontent.com/33997808/35094678-f4310884-fc80-11e7-9b97-47e9617d26d3.png)
@alisahuxu  @georgeliuyu  已完成

**Comment by georgeliuyu** [comment]
@fangrongxaing 不错

**Comment by alisahuxu** [comment]
已经完成。ICP规范，时间仓促。没有PR
