### ISSUE TITLE
icpper的名片设计

### ISSUE THREAD

**Issue by fangrongxaing** [sibbay-ai/operating#153]
为了对外联络的需要，针对icp的贡献者设计电子名片。
内容：
名称抬头：小白健康 icp贡献者
姓名
icp 排名
电话
邮件
github账号
来源issue：https://github.com/sibbay-ai/public/issues/528

**Comment by fangrongxaing** [comment]
deadline 2018-11-3

**Comment by fushang318** [comment]
deadline 格式不对

**Comment by fushang318** [comment]
你没有 @ 任何人，别人如何看到你的 ISSUE

**Comment by fangrongxaing** [comment]
[3.pdf](https://github.com/sibbay-ai/operating/files/2534875/3.pdf)
[1.pdf](https://github.com/sibbay-ai/operating/files/2534876/1.pdf)
[2.pdf](https://github.com/sibbay-ai/operating/files/2534877/2.pdf)

**Comment by fangrongxaing** [comment]
第一款风格设计完毕 @fushang318 @georgeliuyu @ben7th

**Comment by fushang318** [comment]
详细内容会由 ben7th  来看

ICP 规范问题
1. deadline 格式不对
2. 没有PR

**Comment by ben7th** [comment]
![image](https://user-images.githubusercontent.com/322486/47835762-7e872900-dde0-11e8-9473-09247d0f07e0.png)

![image](https://user-images.githubusercontent.com/322486/47835783-965ead00-dde0-11e8-97c5-c1de996401cf.png)

![image](https://user-images.githubusercontent.com/322486/47835802-af675e00-dde0-11e8-8cdb-043d63736313.png)


@fangrongxaing 

建议把图片直接贴在 issue 里，便于大家直观的验收，否则还要下载才能看

- 左下角英文字体不是很合适，建议用较粗的无衬线字体
- 中间的人员信息，建议用无衬线字体，目前的有有衬线字体印刷出来或者在一些设备上显示不清晰
- 三个头部都挺好，我没意见
- 若中间不是刻意留白，内容文字可以居中

**Comment by fangrongxaing** [comment]
OK~

**Comment by fangrongxaing** [comment]
这个是电子名片  应该不涉及到直接打印。而且这个黑色贴边应该是截图留下来的。原稿没有黑边

**Comment by fangrongxaing** [comment]
2018.11.01 更新内容

1.小白上部增加装饰条（目的 左上 右下 匹配 避免上轻下重）
2.小白健康贡献者大小比重增加。
3.左下角字体往中心偏移一部分，字体格式改变。
4.icon图标修正颜色。icp保持原来颜色

**Comment by fangrongxaing** [comment]
<img width="431" alt="2018-11-01 11 08 55" src="https://user-images.githubusercontent.com/33997808/47860570-c7b09a80-de2b-11e8-8d3b-663c20239260.png">

**Comment by fangrongxaing** [comment]
今天晚上已经与黄姐沟通 ，在deadline之前完成任务

**Comment by fangrongxaing** [comment]
@fushang318 @ben7th

**Comment by fushang318** [comment]
1. deadline 格式不对
2. 没有PR

@fangrongxaing

**Comment by ben7th** [comment]
@fangrongxaing 请尽快按照 ICP 规范写明 deadline 申请和发 PR

**Comment by fangrongxaing** [comment]
好的好的==

**Comment by fangrongxaing** [comment]
11.02更新
加入二维码后。是不是使得名片更加有趣
上面的绿色线条 移到底下。变成绿草 。二维码是花朵 。小白捧着花朵对着你微笑

**Comment by fangrongxaing** [comment]
<img width="441" alt="2018-11-02 9 09 25" src="https://user-images.githubusercontent.com/33997808/47917448-90ea8b00-dee4-11e8-96e8-e204e8d99a81.png">

**Comment by fangrongxaing** [comment]
如果没有问题 就采用这个设计了 @fushang318 @ben7th @georgeliuyu

**Comment by ben7th** [comment]
@fangrongxaing 左下角 icp 感觉和上面似乎没对齐（略靠外）
个人信息的文字间距好像不太一样
手机号建议不要中间空格
github 名字前面建议加上 @

就这些了

**Comment by ben7th** [comment]
@fangrongxaing 左下角 icp 感觉和上面似乎没对齐（略靠外）
个人信息的文字间距好像不太一样
手机号建议不要中间空格
github 名字前面建议加上 @

就这些了

**Comment by ben7th** [comment]
@fangrongxaing 左下角 icp 感觉和上面似乎没对齐（略靠外）
个人信息的文字间距好像不太一样
手机号建议不要中间空格
github 名字前面建议加上 @

就这些了

**Comment by fangrongxaing** [comment]
好滴

**Comment by fushang318** [comment]
@fangrongxaing 
1. 你的 deadline 格式不对
2. 没有提交PR


需要按照ICP规范完成以上两项，否则会判定为 变更 deadline

**Comment by pimgeek** [comment]
每次看到由人类发来的，如同IDE Warning Message 格式的出错提醒，常会有种莫名的受辱感 😅

**Comment by fangrongxaing** [comment]
申请开发 deadline:2018-11-03 size:1 @ben7th

**Comment by fangrongxaing** [comment]
😌😌😌

**Comment by fushang318** [comment]
这个设计的目的是制作每一个ICP贡献者的名片，需要提交原始的设计文件，以及各种字体，方便后续随时可以制作新的人员名片 @fangrongxaing

**Comment by fangrongxaing** [comment]
好滴

**Comment by fushang318** [comment]
请提交一个石墨文档，文件放在石墨文档附件中，PR 内容是石墨文档链接和说明即可，参考贾老师的PR @fangrongxaing

**Comment by fangrongxaing** [comment]
<img width="433" alt="2018-11-03 5 28 49" src="https://user-images.githubusercontent.com/33997808/47950552-cba8fd80-df8e-11e8-8bc4-c17a74b271b0.png">

**Comment by fangrongxaing** [comment]
1.字体间距是一致的
2.手机号去除空格
3.@增加。但是不加粗。不协调
4.下面字体偏移了一些

**Comment by fangrongxaing** [comment]
现在 开始制作 他人名片

**Comment by fangrongxaing** [comment]
@ben7th
