### ISSUE TITLE
omaha年会参展海报设计

### ISSUE THREAD

**Issue by fangrongxaing** [sibbay-ai/operating#155]
根据已有模版和已有内容进行海报设计
来源issue：https://github.com/sibbay-ai/medical/issues/289

**Comment by fangrongxaing** [comment]
申请开发 deadline：2018-12-12 size：0.2 @fazhen

**Comment by fangrongxaing** [comment]
@fazhen

**Comment by fazhen** [comment]
小荣，海报设计相关素材，详见https://shimo.im/docs/8bCNqynFFhAoZWPz/ 《参展海报所需相关素材》

如有疑问，请随时联系。 @fangrongxaing

**Comment by fazhen** [comment]
小荣，公司相关介绍文字，已经确认，如下：

**小白健康，一款随时记录健康信息的小程序


人性化互动
轻松生成专属健康日记


一键转发
随时分享个人健康状况


独特奖励模式
记录即可获取Token奖励



小白，记录您的健康足迹**


@fangrongxaing 
请根据文字内容，进行海报设计

**Comment by fushang318** [comment]
变更 deadline：2019-01-15
