### ISSUE TITLE
小白微信公众号软文发布及相关工作

### ISSUE THREAD

**Issue by aixinhuang** [sibbay-ai/operating#157]
关于微信公众号相关主要工作内容如下：
1.参与并完成发布11月25日SHT发放仪式海报（非icpper完成，向财务申请发包）（size：0.2）
2.参与编辑并完成发布“小白健康token首发视频”（size：0.3）
3.参与编辑并完成发布“小白圈地运动”会议视频 （size：0.3）
4.完成“大雪时节”海报设计及发布工作 （size：0.4）

**Comment by aixinhuang** [comment]
申请开发 deadline：2018-12-18 size：2.5 @fazhen

**Comment by aixinhuang** [comment]
申请变更 deadline：2018-12-18 size：2 @fazhen @fushang318

**Comment by fazhen** [comment]
请修改标签 @fushang318
