### ISSUE TITLE
圣诞节海报设计

### ISSUE THREAD

**Issue by aixinhuang** [sibbay-ai/operating#163]
我的主要工作内容为：
1.出圣诞海报概念；
2.制作过程的协调工作；
3.海报验收及在微信公众号完成发布的工作。

- 圣诞海报的目的、概念、要求：
1）小白元旦正式上线前通过微信公众号营造氛围，传递小白有爱，活跃、吸引更多阅读者（粉丝）；
2）体现节日氛围，小白祝你平安、圣诞快乐的信息；
3）海报中体现“2019年1月1日小白健康正式上线”的文字信息；
4）海报中植入小白小程序二维码
5）微信公众号发布日期12月24日（平安夜）

**Comment by fushang318** [comment]
这个是谁的ISSUE

**Comment by fazhen** [comment]
请按照微信沟通内容进行修改 @aixinhuang

**Comment by aixinhuang** [comment]
申请开发 deadline：2018-12-12 size：0.1 @fushang318 @fazhen 
请@fangrongxaing 配合完成 ，谢谢！

**Comment by aixinhuang** [comment]
申请变更 deadline：2018-12-27 size：0.1 @fushang318 @fazhen，变更原因：电脑原因，延长时间

**Comment by fushang318** [comment]
变更 deadline: 2018-12-27
