### ISSUE TITLE
圣诞节海报画图设计

### ISSUE THREAD

**Issue by fangrongxaing** [sibbay-ai/operating#164]
内容：海报的设计

风格 ：延续以往的设计风格。突出家人和小白的联系

图画：一家人和小白围着圣诞树欢乐。体现小白的温暖和家人的快乐

**Comment by fangrongxaing** [comment]
申请开发 deadline：2018-12-25 size：0.5 @aixinhuang

**Comment by aixinhuang** [comment]
请打审核标签@fushang318 @fazhen

**Comment by fushang318** [comment]
@aixinhuang @fangrongxaing OK

**Comment by fazhen** [comment]
申请变更 deadline：2019-01-01 @fushang318

**Comment by fushang318** [comment]
变更 deadline：2019-01-01
