### ISSUE TITLE
小白正式上线公众号发布软文及海报

### ISSUE THREAD

**Issue by aixinhuang** [sibbay-ai/operating#168]
小白新年正式上线，微信公众号将配合发布软文和海报。
我的主要工作内容为：
1.根据刘总提要、宋亮撰写的“4个一，1个感谢”文章，编辑成一片微信公众号软文，让阅读者了解小白健康，并发布。
2.出小白新年正式上线海报概念；
3.制作过程的协调工作；
4.海报验收及在微信公众号完成发布的工作。
新年上线海报的目的、概念、要求：
1）小白元旦正式上线，微信公众号发布告知更多人，吸引更多人进入小程序，成为小白健康新用户；
2）明确体现“2019年1月1日小白健康正式上线”的重要信息，节日氛围烘托，并有新年快乐内容；
4）海报中植入小白小程序二维码；
5）微信公众号发布日期2018年12月31日。

**Comment by aixinhuang** [comment]
申请开发 deadline：2019-1-2 size：0.3 @fushang318 @fazhen
上线海报请@fangrongxaing 配合完成 ，谢谢！

**Comment by fushang318** [comment]
申请格式是
```
申请开发 deadline: 2019-01-02 size：0.3
```

@aixinhuang 你可以编辑一下你写的申请格式，现在编辑是可以的

**Comment by aixinhuang** [comment]
已修改，谢谢！@fushang318

**Comment by fushang318** [comment]
@fazhen

**Comment by aixinhuang** [comment]
收到@fazhen

**Comment by aixinhuang** [comment]
申请变更 deadline: 2019-01-05  size：0.5 
变更原因：deadline-预留走流程时间不够，size-新增文案内容
@fazhen @fushang318

**Comment by fushang318** [comment]
变更 deadline: 2019-01-05 size：0.5
