### ISSUE TITLE
开放医疗与健康联盟第三届年会参会事宜

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/operating#17]
OMAHA联盟即将于2018年1月20日在杭州举行第三届年会，小白健康作为机构会员参加。
1.我和刘总 @georgeliuyu 将于本周六（2018-01-20）参会，以便了解前沿资讯;
2.关于本次会议，是否需要以小白健康的名义撰写一篇会议报道？ @alisahuxu

**Comment by alisahuxu** [comment]
谢谢，很有报道价值。麻烦提供一些可以分享的照片。
文字就麻烦你了！@fazhen

**Comment by fazhen** [comment]
好的 @alisahuxu

**Comment by fazhen** [comment]
**目的**：了解医疗信息技术前沿资讯，以小白健康的名义撰写会议报道。
**Deadline**：2018-01-22
**Size**:2d @georgeliuyu

**Comment by georgeliuyu** [comment]
@fazhen 这样吧！也就一天的会，反正我要去，你就不用去了。

**Comment by fazhen** [comment]
好的，但是会议报道可能就无法撰写了或者您这里如果能收集到现场资料也可以大概撰写一篇 @georgeliuyu 
是否需要撰写会议报道，请小胡决定 @alisahuxu

**Comment by alisahuxu** [comment]
我和OMAHA的美丽沟通一下。@fazhen
