### ISSUE TITLE
推广视频剪辑修改

### ISSUE THREAD

**Issue by fangrongxaing** [sibbay-ai/operating#171]
和南希合作修改推广视频
内容：修改剪辑推广视频

**Comment by fangrongxaing** [comment]
申请开发 deadline：2019-01-15 size：1 @fushang318

**Comment by fushang318** [comment]
这个 ISSUE 废弃，改成 https://github.com/sibbay-ai/operating/issues/177

**Comment by fushang318** [comment]
这个任务的 PR 是 https://github.com/sibbay-ai/operating/pull/176
