### ISSUE TITLE
2019年春节牵金猪活动海报设计及软文发布相关工作

### ISSUE THREAD

**Issue by huangaixin** [sibbay-ai/operating#178]
微信公众号配合2019年春节期间“牵金猪”活动，发布软文及海报。
我的主要工作内容为：
1.编辑微信公众号软文，并发布。
2.与出除夕、春节二个海报概念；
3.制作过程的协调工作；
4.海报验收及在微信公众号完成发布的工作。
2019年春节期间“牵金猪”海报的目的、概念、要求：
1）有牵金猪活动告知内容，根据排版用春节承托活动主题，目的在于以活动本身帮助老用户拉新，吸引更多人关注小白健康，成为新用户；
2）体现春节祥和喜悦，节日氛围烘托，并有除夕、新春快乐之类的内容；
4）海报中植入小白小程序二维码；
5）二次微信公众号发布日期2019年2月4日、2月5日。

**Comment by huangaixin** [comment]
申请开发 deadline：2019-03-10 size：0.5 @fushang318 @fazhen
海报设计请@fangrongxaing 配合完成 ，谢谢！

**Comment by fazhen** [comment]
已经审核，请修改标签 @fushang318

**Comment by fazhen** [comment]
此issue系黄老师登陆另外一个账号发布的issue，她已经重新发布，请不要处理，不必修改标签，以免重复统计 @fushang318
