### ISSUE TITLE
2019年1月每日提示语 

### ISSUE THREAD

**Issue by huangaixin** [sibbay-ai/operating#179]
2019年1月份每日提示语主要工作内容如下：
内容以介绍小白健康小程序功能为主，通过简要文字增加用户对小白健康各项功能的熟悉度。
时间段1月1日-1月31日，为期31天，
每天撰写或编辑小白互动对话页面每日提示语。

**Comment by huangaixin** [comment]
申请开发 deadline：2019-02-10 size：1 @fazhen @fushang318

**Comment by fushang318** [comment]
1

**Comment by fushang318** [comment]
账号不对
