### ISSUE TITLE
小白宣传视频的改良方案和讨论

### ISSUE THREAD

**Issue by fangrongxaing** [sibbay-ai/operating#192]
内容：上一个版本的宣传视频需要进行改良，为此需要做几个改良的方案，改良方案后进行讨论

**Comment by fangrongxaing** [comment]
申请开发 deadline：2019-03-15 size：1 @fushang318

**Comment by fangrongxaing** [comment]
我们把2019年1月设计的视频版本称为V1。本次提出的改进方案是围绕v1进行改良设计。
通过分析ｖ1版本和结合一些观看人员的意见，可以总结如下的不足。
方案一 concept one （对视频进行小改动，保持平面化风格）
方案二 concept two （现实与平面化风格拼搭，对视频进行大范围改动）

**Comment by fangrongxaing** [comment]
@nancy919

**Comment by nancy919** [comment]
确认于2月19日周日上午，同宋亮、刘总和小嵘一起就小白的宣传视频的改良方案进行讨论
