### ISSUE TITLE
微信公众号编辑发布及相关工作

### ISSUE THREAD

**Issue by aixinhuang** [sibbay-ai/operating#196]
3/8-4/12微信公众号主要工作内容：
1.编辑或配图到发布投稿人的软文
1）小白用户Dora 1篇，编辑，其中配图为我拍的照片；
2）贡献者贾老师2篇，图文均为作者本人所做，仅发布
2.设计制作海报并发布（3.8妇女节/世界卫生日）
3.原创2篇软文（3/13呼应Dora文章及4/5清明主题）
4.转载“小白健康众合社区201903月报”

**Comment by aixinhuang** [comment]
申请开发 deadline：2019-04-16 size：2  @fazhen

**Comment by fazhen** [comment]
请修改标签 @fushang318

**Comment by fushang318** [comment]
变更 deadline: 2019-5-16
