### ISSUE TITLE
小白健康用户群维护及文案相关

### ISSUE THREAD

**Issue by aixinhuang** [sibbay-ai/operating#198]
主要工作内容：
1.从2月份开始进行种子用户群维护，用音乐、图片及问候的形式提升群的活跃度，为未来社群管理做尝试。
2.从3月25日图片改为加文字及小白健康水印的初级海报，以增加大家对小白健康的认知度和阅读性、传播性。
3.“听说用小白健康挺好用的”文案组图

**Comment by aixinhuang** [comment]
申请开发@fushang318

**Comment by fushang318** [comment]
https://shimo.im/docs/efGTPEDIx08H2GIU/ 《听说小白健康挺好用的(组图文案)》
这种做法感觉容易出现版权纠纷呀
