### ISSUE TITLE
小白海报模板合集设计

### ISSUE THREAD

**Issue by fangrongxaing** [sibbay-ai/operating#202]
内容来源：https://github.com/sibbay-ai/feedback/issues/180#event-2326413175
风格要求：简洁、优美
要素：包含小程序二维码，小白形象和双人logo
两种尺寸：
1、900px x 383px 公众号封面
2、720px x 1280px 手机海报
做成模板放在：https://www.fotor.com.cn/

**Comment by fangrongxaing** [comment]
申请开发 deadline：2019-05-15 size：2 @fushang318

**Comment by fangrongxaing** [comment]
审核：南希 @nancy919

**Comment by nancy919** [comment]
审核通过
