### ISSUE TITLE
血压测量操作步骤图

### ISSUE THREAD

**Issue by fangrongxaing** [sibbay-ai/operating#204]
1、保留文字内容，重新设计界面；
2、共9张图；
3、尺寸：宽750 *高不限
内容来源：https://github.com/sibbay-ai/feedback/issues/231

**Comment by fangrongxaing** [comment]
申请开发 deadline：2019-06-15 size：1.5 @fushang318

**Comment by fangrongxaing** [comment]
审核：南希 @nancy919

**Comment by nancy919** [comment]
已验收

**Comment by fangrongxaing** [comment]
这是原来的操作图
需要重新设计一款
<img width="502" alt="58227024-b8f3eb80-7d5b-11e9-95c1-581acb0d39a3" src="https://user-images.githubusercontent.com/33997808/59513076-a731de00-8eec-11e9-9145-fc7d2403a48b.png">

**Comment by fangrongxaing** [comment]
原图的产品图片太过零碎，所以我想让里面的图画整合，形成一个套系。而不是一个操作对应一个工具。
然后配色采用小白最新色系
![3641558010023_ pic](https://user-images.githubusercontent.com/33997808/59513229-ff68e000-8eec-11e9-9312-09323e6e3176.jpg)

**Comment by fangrongxaing** [comment]
然后第一轮的方案
![3861559743833_ pic_hd](https://user-images.githubusercontent.com/33997808/59513279-1dcedb80-8eed-11e9-85b7-62d949c769ca.jpg)
里面设计了两个主角，一男一女
然后其中的正确步骤由主角去演示
在特殊的操作的地方采用局部放大的设计。

**Comment by fangrongxaing** [comment]
通过和南希讨论
发现的问题
![8231559871764_ pic](https://user-images.githubusercontent.com/33997808/59513481-7f8f4580-8eed-11e9-805b-d6b0cf818a55.jpg)
1.图片太灰了
2.字体太小
3.特殊部位没有提示
然后加了一张建议图
![8301559873677_ pic](https://user-images.githubusercontent.com/33997808/59513575-b82f1f00-8eed-11e9-883d-19c09c68e164.jpg)

**Comment by fangrongxaing** [comment]
第二轮方案在第一轮上进行优化
因为使用人群为老年人，所以字体变大了并且去除了一些字体
背景整体变白 ，使图片更加清晰
加上了准确的图案的表现
加上红圈来表示局部的特殊性

**Comment by fangrongxaing** [comment]
![8381559878429_ pic](https://user-images.githubusercontent.com/33997808/59513893-6044e800-8eee-11e9-9cb8-0f69dc7d35a1.jpg)
![8391559878429_ pic](https://user-images.githubusercontent.com/33997808/59513900-61761500-8eee-11e9-9761-79d39d769836.jpg)
![8401559878429_ pic](https://user-images.githubusercontent.com/33997808/59513903-633fd880-8eee-11e9-8890-4b22db03fd75.jpg)
![8411559878429_ pic](https://user-images.githubusercontent.com/33997808/59513908-64710580-8eee-11e9-9b5f-840a5b7c1647.jpg)
![8421559878430_ pic](https://user-images.githubusercontent.com/33997808/59513911-65a23280-8eee-11e9-8cc6-fa8092333bc0.jpg)
![8431559878430_ pic](https://user-images.githubusercontent.com/33997808/59513914-66d35f80-8eee-11e9-9070-44a75814107a.jpg)
![8441559878430_ pic](https://user-images.githubusercontent.com/33997808/59513918-68048c80-8eee-11e9-8467-0430a3c06016.jpg)
![8451559878430_ pic](https://user-images.githubusercontent.com/33997808/59513922-6935b980-8eee-11e9-9957-7acd1c8a9454.jpg)
![8501559882666_ pic](https://user-images.githubusercontent.com/33997808/59513924-6c30aa00-8eee-11e9-8d93-d6a5db685162.jpg)
![8551559882997_ pic](https://user-images.githubusercontent.com/33997808/59513950-76eb3f00-8eee-11e9-90e4-1d3f4eeb30ee.jpg)

**Comment by fangrongxaing** [comment]
最后结束了这个设计。
得出的结论
1.设计要已人为主，字体的大小和图片的大小要适当变换，不能为了美观而美观
2.设计要与屏幕背景相互结合
3.重要的核心局部要适当凸显，不然用户会不知道
