### ISSUE TITLE
经期互动推广的设计海报

### ISSUE THREAD

**Issue by fangrongxaing** [sibbay-ai/operating#205]
广告语：
我们的智能记录，
更加智能。
尺寸：
750 *1334
内容来源：https://github.com/sibbay-ai/feedback/issues/230

**Comment by fangrongxaing** [comment]
申请开发 deadline：2019-06-15 size：1.5 @fushang318

**Comment by fangrongxaing** [comment]
审核：南希 @nancy919

**Comment by nancy919** [comment]
已验收

**Comment by fangrongxaing** [comment]
第一轮 收集参考图片
并与南希 黄姐 以及刘总 开会
开会内容：针对各自的方案寻找方向。
以下是第一次的寻找的参考图片
![图片 1](https://user-images.githubusercontent.com/33997808/59509187-efe49980-8ee2-11e9-80f6-401c98e4f2ee.png)
![2](https://user-images.githubusercontent.com/33997808/59509193-f3782080-8ee2-11e9-8972-7ceb4d12a3d5.png)
这两张图片的原本含义是：花如同女人，但是月经如同铁锁般阻挡女人的生活
这两张图片经过讨论，不适合这个海报的方向。
原因是：1.图片太过压抑，给人一种心情不愉悦的感受
2.给人一种恐吓式的做法
所以经过商讨不适合这个方向

**Comment by fangrongxaing** [comment]
第二个方向是愉悦的方向
![2](https://user-images.githubusercontent.com/33997808/59510092-68e4f080-8ee5-11e9-902a-3df2e940be45.png)
这张图片的含义是快乐，表示女生用小白健康很快乐。
但是经过商讨，不适合这个海报的方向。
原因是：1.图片没有展示小白产品的内容
2.图片展现的很虚空，没有实际的作用

**Comment by fangrongxaing** [comment]
然后最后一个方向是感悟的方向
![4](https://user-images.githubusercontent.com/33997808/59511372-a7c87580-8ee8-11e9-9443-0ebd6c5b18f9.png)
这张图片的含义是
通过自然有人的关系，表示女人在人生的长路中前进，需要小白给她起到平衡作用。
但是经过商讨，不适合这个海报的方向。
原因是：1.图片过于抽象，不切实际
2.没有表现产品的核心卖点

**Comment by fangrongxaing** [comment]
三个方向都被pass了
最重要的原因是因为没有表现出“different”的想法
刘总建议是用一句话去表现产品的所有思想。并讲了一个乔布斯扔纸团的思维的故事。
所以我们需要一句关键词汇去当咋们海报的广告词
对于广告的内容是什么，通过讨论
我们确定是“淘宝买家的评论”方式来设计海报
也就是通过真实的模拟使用环境来表达出小白的核心思想。
然后下个阶段 我和南希合作，设计出这个画稿

**Comment by fangrongxaing** [comment]
![6191558786009_ pic](https://user-images.githubusercontent.com/33997808/59511914-1d811100-8eea-11e9-8193-07778223649f.jpg)
刘总建议使用这张当作颜色的色系参考背景

**Comment by fangrongxaing** [comment]
第二轮的设计稿
第二轮：
和南希讨论，是不是可以用直观的方式去表现咋们的产品，在加上一句核心的广告词
![6651558844683_ pic_hd](https://user-images.githubusercontent.com/33997808/59512081-85cff280-8eea-11e9-97e4-4c57cd806917.jpg)
参考图片来自南希发的iPhone的宣传图，一个手机配上一句话。
于是做了下面的两个方案
![6821558866027_ pic_hd](https://user-images.githubusercontent.com/33997808/59512173-c16abc80-8eea-11e9-9914-7404b0758df8.jpg)
通过小白的截屏来反映产品的功能。其中一套配色采用新的设计。
标题语为 我们的智能记录 更加智能

**Comment by fangrongxaing** [comment]
然后和刘总 南希在开了第二轮的会议
刘总很不满意这个设计
因为这种表现方式很烂，没有创意，没有思想。
所以第二轮的设计又被pass了。
得出的结论是：海报需要创新，即使同样的内容也需要一种新颖的方式
于是刘总提出了新的参考图片

![mmexport1559136389744](https://user-images.githubusercontent.com/33997808/59512550-8b7a0800-8eeb-11e9-8ac8-6aae9b369bd3.jpg)
![mmexport1559136391927](https://user-images.githubusercontent.com/33997808/59512561-8fa62580-8eeb-11e9-9e96-e2636fbea887.jpg)
![mmexport1559136413776](https://user-images.githubusercontent.com/33997808/59512567-92087f80-8eeb-11e9-9112-97691558c52f.jpg)

**Comment by fangrongxaing** [comment]
通过和南希讨论，开始设计第三轮方案
借鉴参考图片，通过纸代替屏幕。字迹代替对话。这种形式把产品交互“跃然纸上”的贴切感。
于是设计了第三轮的设计稿
![经期互动推广的设计海报](https://user-images.githubusercontent.com/33997808/59512792-0c390400-8eec-11e9-9d7d-abb257fa19a8.jpg)
通过采用推荐的配色
把小白和用户的对话用纸张的方式记录下来，也表现了小白“记录”的核心。

**Comment by fangrongxaing** [comment]
到此，设计就结束了，我感觉设计的不是很好。
1.海报太平，没有立体的做反衬。
2.不够精细
下次需要做的更好
