### ISSUE TITLE
2019年5月 ICP 补充申请

### ISSUE THREAD

**Issue by aixinhuang** [sibbay-ai/operating#212]
aixinhuang 2019年5月 ICP 补充申请
类别：小白健康运营工作

Ieeues：
2019年4-5月每日互动首语 · Issue #208 · sibbay-ai/operating  https://github.com/sibbay-ai/operating/issues/208

PR：
4-5月每日互动首语 by aixinhuang · Pull Request #209 · sibbay-ai/operating  https://github.com/sibbay-ai/operating/pull/209

SIZE:2

**Comment by aixinhuang** [comment]
原因: 因自身时间原因, 导致在 2019-05-15 之前无法将这个 icp issue 正确的标签, 同时该issue 的工作 PR 已经合并, 导致这个 issue 无法被 icp 系统识别， 故在此申请补充这个 icp issue
共计 size: 2.0
请 @fushang318  @Jessica124 审核

**Comment by Jessica124** [comment]
同意

**Comment by Jessica124** [comment]
同意

**Comment by fushang318** [comment]
已经处理
