### ISSUE TITLE
众合社区月报编辑及发布工作

### ISSUE THREAD

**Issue by aixinhuang** [sibbay-ai/operating#219]
主要工作内容：
4月开始到7月的小白健康众合社区的月报由我汇集相关信息编辑并发布，第52期-55期一共4期。
（由宋亮及财务提供月报相关信息，其中财务的数据换算成金额由我完成）

**Comment by aixinhuang** [comment]
申请开发 deadline；2019-08-20 size：0.6 @fushang318

**Comment by fushang318** [comment]
变更 deadline: 2019-8-15
