### ISSUE TITLE
补发：一月内容撰写的安排及和贾发振的沟通

### ISSUE THREAD

**Issue by alisahuxu** [sibbay-ai/operating#23]
@georgeliuyu [审核一月文稿，以及与贾发振确定撰稿的频率、人手、内容方式、供稿的价格等等。3小时。](https://github.com/sibbay-ai/operating/issues/5)

**Comment by georgeliuyu** [comment]
@alisahuxu 审核结果的提交物：应该确认文稿的链接（石墨）

**Comment by alisahuxu** [comment]
@georgeliuyu https://shimo.im/docs/hKl2G9dtH5MSmf2M，其中一篇。
剩下三篇：https://shimo.im/folder/Yx8l2uI6iJgdo8wk
共计四篇，以上。
