### ISSUE TITLE
请制作腊八节的闪图@小嵘

### ISSUE THREAD

**Issue by alisahuxu** [sibbay-ai/operating#26]
规则和以前一样，制作闪图，节日时间：1月24日。 @fangrongxaing

**Comment by fangrongxaing** [comment]
收到

**Comment by fangrongxaing** [comment]
![9](https://user-images.githubusercontent.com/33997808/35194513-c6c4004c-feef-11e7-9832-6eb35a1e3688.png)
@georgeliuyu

**Comment by alisahuxu** [comment]
此项工作已经完成，因临时规范ICP流程，时间仓促，没有PR
