### ISSUE TITLE
元旦闪图@小嵘

### ISSUE THREAD

**Issue by alisahuxu** [sibbay-ai/operating#3]
微信公众号推送元旦闪图。文案：
option1:  2018   贺新年 迎健康 ——小白健康小程序
option2:  新的一年  让智能数据管理你的健康  小白健康小程序  恭祝元旦快乐
option3:  2018  让小白为您开启智能健康的365天  元旦快乐  

@小嵘  @georgeliuyu

**Comment by georgeliuyu** [comment]
@alisahuxu 小嵘是 @fangrongxaing

**Comment by georgeliuyu** [comment]
@alisahuxu option2

**Comment by alisahuxu** [comment]
@georgeliuyu 收到。是该有一份通讯录了，大家的名字在不同的软件上都不一样。

**Comment by alisahuxu** [comment]
已完成

**Comment by georgeliuyu** [comment]
@fangrongxaing 你需要提出工作量，@alisahuxu 在同意的基础上，你需要标注size的label

**Comment by fangrongxaing** [comment]
元旦闪图 工作量 八个小时

**Comment by alisahuxu** [comment]
同意。

**Comment by georgeliuyu** [comment]
![image](https://user-images.githubusercontent.com/16983441/35022542-7014205a-fb71-11e7-8458-2e878776448b.png)

要这样写

**Comment by fangrongxaing** [comment]
补发
![default](https://user-images.githubusercontent.com/33997808/35094928-cddcd2de-fc81-11e7-8cdb-f049a5c0469b.png)
![2](https://user-images.githubusercontent.com/33997808/35094954-dfd6bb26-fc81-11e7-84e2-9119f47f7c99.png)
![default](https://user-images.githubusercontent.com/33997808/35095089-40ef7bc8-fc82-11e7-8dce-ad1d30ecba62.png)
