### ISSUE TITLE
新年测体重活动内容及规则

### ISSUE THREAD

**Issue by alisahuxu** [sibbay-ai/operating#33]
@fushang318 根据以下协作的要求，给出活动内容及规则：
内容：
新年添福不添肉——小白健康2018年新春特别企划：凡是新年七天坚持记录体重的用户，将有机会获取神秘大奖一份，名额有限，坚持就是胜利！

活动时间：2018年2月15日—2018年2月21日
活动规则：
1.所有小白健康·小程序的用户均可参加。
2.在活动规定期间，每天录入自己的体重数值。小程序会为每位用户计算出和前一日的差值：增加为正数，减少为负数。小程序每日汇集以上所有用户的差值，平均后得出的数值，将会添加到卡通人物小白的身上，并与次日公布。
3.活动最后一天：2018年2月21日，体重变化数值最接近卡通人物体重变化数值的前三名用户，将分别获得小白健康送出的神秘大奖一份。
4.活动最终结果将于2018年2月22日公布在小白健康的微信公众号上，获奖的三位用户将收到小程序推送的获奖通知，请及时留下手机号码，方便我们为您邮寄礼品。
5.因为当日的数据是以前一日为基础的，所以请每位用户一定要坚持记录体重（活动共七天），否则将无缘角逐最后的大奖。

> https://github.com/sibbay-ai/cooperation-issues/issues/248#issuecomment-361198566
![qq20180130-0](https://user-images.githubusercontent.com/34643533/35549811-53dd6918-05c2-11e8-922f-e476e8b8757f.png)

**Comment by fushang318** [comment]
@alisahuxu 收到，我把内容增加到脚本中

**Comment by alisahuxu** [comment]
@fushang318 
根据以下协作的要求，给出活动7天的问候：

除夕：
除夕之夜，团团圆圆
参与我们的新年活动吧！

初一：
吉星高照，开春送福
今天你记录了吗？

初二：
串门拜年，红包拿来
今天你记录了吗？

初三：
懒觉睡饱，神清气爽
今天你记录了吗？

初四：
迎接灶神，口福满满
今天你记录了吗？

初五：
财神敲门，好运难挡
今天你记录了吗？

初六：
开门利市，财源滚滚
今天你记录了吗？
大奖就要揭晓咯~


![qq20180131-3](https://user-images.githubusercontent.com/34643533/35612344-789bee6e-06a3-11e8-8c4a-db6059c56824.png)

**Comment by alisahuxu** [comment]
@fushang318 如果你觉得文案不OK，我这边再做修改。你先用着。

**Comment by fushang318** [comment]
@alisahuxu 哈哈，我不懂啦，你觉得OK就可以了，我添加进去

**Comment by alisahuxu** [comment]
@alisahuxu 申请开发 size:0.2 Deadline: 2018-01-31
