### ISSUE TITLE
审核——年会邀请函设计，且上传至微信公众后台。

### ISSUE THREAD

**Issue by alisahuxu** [sibbay-ai/operating#34]
多次沟通审核后，完成年会邀请函及相关图片制作。如下：
![000](https://user-images.githubusercontent.com/34643533/35510967-2347ff12-0535-11e8-9ced-752eac8c3521.png)
![001](https://user-images.githubusercontent.com/34643533/35512887-2d72f8aa-053c-11e8-8c69-ccf9e51f8bfc.png)

并将36名嘉宾信息及会议地址上传至微信公众后台。

**Comment by alisahuxu** [comment]
@shero以下邀请函制作完毕。
![000](https://user-images.githubusercontent.com/34643533/35513008-98489482-053c-11e8-8ddc-fdfdebeb23fb.png)
可于2月2日至5日，对外发布。

**Comment by alisahuxu** [comment]
![-](https://user-images.githubusercontent.com/34643533/35603008-22ba1354-0676-11e8-9818-8c130454ec7a.jpeg)
@shero3。以上是定稿。
@georgeliuyu   审核工作完成。size:1

**Comment by georgeliuyu** [comment]
@alisahuxu 你看看icp的流程图的要求，要按照规范的申请文字撰写。
@shero3 以后小胡的icp label由你来打。

**Comment by shero3** [comment]
@alisahuxu 对外发布是什么意思？

**Comment by alisahuxu** [comment]
@shero3 我记得刘总说过：以后以公司名义对外发布的东西，要先给到你。邀请函应该算吧，哈哈

**Comment by shero3** [comment]
@alisahuxu 这个邀请函是发布给特定的人，还是可以公开发布的

**Comment by alisahuxu** [comment]
@shero3 可以公开。

**Comment by alisahuxu** [comment]
此项工作已经完成。但是，临时规范ICP流程，没有做PR。
