### ISSUE TITLE
新年测体重活动-第一波宣传漫画-脚本文案

### ISSUE THREAD

**Issue by alisahuxu** [sibbay-ai/operating#35]
@[alisahuxu] 申请开发 size:[0.3] Deadline: [2018[-12][-31]]
题目：《胖小白的新年心事》
P1：新衣服好看可惜太紧，我只能穿宽松的旧衣服。（画面：几个小朋友穿着新衣服，胖小白在角落抬不起头，衣服颜色灰旧、松松垮垮）
P2：表弟给奶奶磕头就领了大红包，可是我连弯腰都困难。（画面：表弟手举红包喜笑颜开，奶奶微笑坐着等胖小白磕头，胖小白满脸通红，肚子很大，扣子崩开）
P3：他们说年夜饭的红烧肉很赞，是真的吗？（画面：胖小白捧着空碗，幻想一盘油汪汪的红烧肉，流口水）
P4：这个新年，我要用小白健康记录体重，督促自己成为健康苗条的胖小白！（胖小白立于画面中央，表情严肃笃定，站在体重秤上，画面一边是小白健康·小程序）

以上四个画面都要加入小程序二维码。

以下为参考图片：
![836013c6a64ca58](https://user-images.githubusercontent.com/34643533/35569666-b0ae3768-0607-11e8-883d-b3581fd41389.jpg)

@fangrongxaing 
这是第一波宣传，最晚2月10日给我。

**Comment by fangrongxaing** [comment]
收到 @alisahuxu

**Comment by fangrongxaing** [comment]
初稿  大致的感觉
![99](https://user-images.githubusercontent.com/33997808/35777940-6a5f9656-09f1-11e8-9fe3-3c446c8138cf.png)

**Comment by fangrongxaing** [comment]
@alisahuxu

**Comment by alisahuxu** [comment]
@fangrongxaing ：

整体风格和画面连贯性设计的很棒。

有几点修改建议：
1. 小白没有四肢，且原本形象就是胖胖的，很难有肢体语言表达幽默，建议更换一个人类小男孩的形象。
2. 以后我们可以创建一个“小白健康”卡通人物家族，不用所有的形象都由小白一个人承担。（对于1.的补充）
3. 具体细节如下。

![image](https://user-images.githubusercontent.com/34643533/35778929-4a45d40c-0a00-11e8-979d-dc2d39cbc1a9.png)
![image](https://user-images.githubusercontent.com/34643533/35778949-87f1a1aa-0a00-11e8-8927-bb8599947966.png)
![image](https://user-images.githubusercontent.com/34643533/35778957-a9565da4-0a00-11e8-97b4-0e9835fdaa35.png)
