### ISSUE TITLE
立春闪图需求

### ISSUE THREAD

**Issue by alisahuxu** [sibbay-ai/operating#36]
@fangrongxaing 一年之计在于春，健康生活在于此——小白健康·小程序
规格和之前一样。2月4日立春，请在之前给到我。

**Comment by fangrongxaing** [comment]
收到 @alisahuxu

**Comment by fangrongxaing** [comment]
请选择一个 @alisahuxu 
![5](https://user-images.githubusercontent.com/33997808/35716396-a4312b54-0813-11e8-92d5-b11888228c4e.png)

![4](https://user-images.githubusercontent.com/33997808/35716902-b629d100-0816-11e8-83e1-ec3c80279f18.png)
![3](https://user-images.githubusercontent.com/33997808/35716997-63d67b5a-0817-11e8-93a2-545bc6feb60a.png)

**Comment by alisahuxu** [comment]
![default](https://user-images.githubusercontent.com/34643533/35773909-91b7315c-099a-11e8-8a8e-e283445b2d81.jpeg)

**Comment by fangrongxaing** [comment]
@alisahuxu  申请开发 size:1 Deadline: 2018-02-03
