### ISSUE TITLE
微信文章，初稿完成，完善中

### ISSUE THREAD

**Issue by alisahuxu** [sibbay-ai/operating#4]
12月30日，贾发振完成微信文章《小白健康：智能健康数据管理家》初稿

**Comment by georgeliuyu** [comment]
@fazhen 完成请将内容的链接回复在这里！

**Comment by fazhen** [comment]
好的，我以附件的形式添加进来 @georgeliuyu @alisahuxu

**Comment by fazhen** [comment]
本文标题《小白健康：智能健康数据管家》
本文目的：向普通用户介绍什么是小白健康？有哪些功能？同时引出健康数据的理念，为后期“智慧医疗”相关文章撰写做铺垫。
 关于文章主题、内容，大家有无其他意见？我再做调整修改。
[20171230-sibbay-jfz-V1.docx](https://github.com/sibbay-ai/operating/files/1596664/20171230-sibbay-jfz-V1.docx)

**Comment by fazhen** [comment]
@alisahuxu @georgeliuyu

**Comment by alisahuxu** [comment]
@fazhen 我仔细阅读了你的文章。作为普通用户的入门读物，我觉得挺好。但是，我们的受众可能层次和知识体系大相径庭，所以，文章开头能否调整一下？不用传统的论文格式。供参考~~

**Comment by fazhen** [comment]
格式可以根据你们运营需要进行调整，文章内容是否需要修改？文章标题是否修改为“小白健康：您的智能健康数据管家”更合适？ @alisahuxu

**Comment by georgeliuyu** [comment]
@alisahuxu @fazhen 我们文档的撰写，建议采用石墨文档。

**Comment by georgeliuyu** [comment]
都放在 ：https://shimo.im/folder/ooU6pr2cMhwCJ6ZS

**Comment by alisahuxu** [comment]
考虑到微信的用户习惯，我对开头做了改编：https://shimo.im/docs/hKl2G9dtH5MSmf2M
@fazhen 欢迎探讨。

**Comment by fazhen** [comment]
开头的修改我这里没有什么意见，参考文献是否需要标注？在石墨上均未显示，如果需要，我可以手工添加 @alisahuxu

**Comment by alisahuxu** [comment]
好的。

**Comment by fazhen** [comment]
ff

**Comment by fazhen** [comment]
我不确定“小白健康白皮书”是否对外开放，所以参考文献中只给出了官网的地址 ，并未给出实际链接，如果可以就没什么问题了 @alisahuxu

**Comment by fazhen** [comment]
还有就是石墨文档中无法进行上角标的修改，请将文章导出后，自行修改参考文献的上角标 @alisahuxu

**Comment by alisahuxu** [comment]
明白，我会修改上角标的。
