### ISSUE TITLE
2018年1月剩余三篇文章撰写主题及内容

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/operating#5]
1.主题：儿童冬季常见疾病
背景：进入冬季后各大医院儿科门诊均超负荷接诊患者，但大部分是儿科常见疾病，在社区医院即可处理。请撰写一篇科普性文章，介绍儿科冬季常见疾病，缓解家长焦虑情绪，分流大医院就诊压力。
要求：①患者教育性质的科普软文，通俗易懂；②字数1200-1500；③涉及参考文献请标注。
报酬：150元

2.主题：糖尿病治疗中患者常见认识误区。
背景：糖尿病患者治疗过程中存在很多认识误区，如糖尿病只控制血糖即可、血糖正常后无需继续服药、不能吃水果等。请撰写一篇科普性文章，介绍糖尿病治疗过程中常见误区，以期患者规范治疗，获得更好的治疗效果。
要求：①患者教育性质的科普软文，通俗易懂；②字数1200左右；③涉及参考文献请标注。
报酬：150元

3.主题：高血压的危害
背景：高血压既是一种独立的疾病，同时又与冠心病、肾功能障碍、心脏病及脑卒中的发生存在明显的因果关系，而由此导致的心血管疾病已经成为成年人猝死的主要杀手。请撰写一篇科普软文，介绍高血压有哪些危害，以期患者正视该病，规范合理使用降压药。
要求：①患者教育性质的科普软文，通俗易懂；②字数1200-1500左右；③涉及参考文献请标注。
报酬：150元

**Comment by fazhen** [comment]
本月剩余三篇医学文章主题及内容如上，请审核 @alisahuxu @georgeliuyu @fushang318 @fangrongxaing @sibbay-devops

**Comment by fushang318** [comment]
@fazhen 
额，抱歉，这个我不太懂，需要我做什么吗？

**Comment by fazhen** [comment]
主要是想参考一下大家的想法，如果有其他的建议可以说一下，我结合医学内容可以做调整 @fushang318

**Comment by georgeliuyu** [comment]
@fazhen 这个不用发给 @fushang318 审核

**Comment by fazhen** [comment]
这个排期你是否认可 @alisahuxu

**Comment by alisahuxu** [comment]
可以的。开始吧。
