### ISSUE TITLE
文章修改润色

### ISSUE THREAD

**Issue by skytian1** [sibbay-ai/operating#60]
来自#57
 已完成文章润色：https://shimo.im/docs/Dt9k6pjOtWwn28A1 
@alisahuxu

**Comment by skytian1** [comment]
已经再次修改润色 @alisahuxu 
https://shimo.im/docs/Dt9k6pjOtWwn28A1

**Comment by skytian1** [comment]
@alisahuxu 申请开发 size:0.3 Deadline: 2018-03-24

**Comment by skytian1** [comment]
最新润色 @alisahuxu https://shimo.im/docs/Dt9k6pjOtWwn28A1

**Comment by skytian1** [comment]
Deadline: 2018-03-24

**Comment by alisahuxu** [comment]
deadline:2018-04-15
