### ISSUE TITLE
小白健康使用过程中，问题及建议汇总。

### ISSUE THREAD

**Issue by alisahuxu** [sibbay-ai/operating#62]
@fushang318  申请开发 size:3 Deadline: 2018-04-01
在使用小白的过程中，从用户的视角，发现问题，汇总于此。

**Comment by alisahuxu** [comment]
https://shimo.im/docs/zXNx40kFwgw3ajla
@fushang318 这是我目前提供的12个问题，待更新。

**Comment by fushang318** [comment]
@alisahuxu 收到

**Comment by alisahuxu** [comment]
又更新了一个问题。链接：https://shimo.im/docs/zXNx40kFwgw3ajla

**Comment by alisahuxu** [comment]
@ax003d
昨天例会讨论后，刘总说对接你就可以了。

**Comment by ax003d** [comment]
@alisahuxu 好的，我今天看看

**Comment by ax003d** [comment]
@alisahuxu 石墨文档中提出的问题，我都已经在上面评论，并且开了相关的 issue 进行后续的跟进。

**Comment by alisahuxu** [comment]
收到。谢谢。等周日产品经理会议之后，我再更新。




| |
alisa
邮箱：alisa_huxu@126.com
|

签名由 网易邮箱大师 定制

在2018年03月23日 16:05，ax003d 写道：

@alisahuxu 石墨文档中提出的问题，我都已经在上面评论，并且开了相关的 issue 进行后续的跟进。

**Comment by alisahuxu** [comment]
15.必须关联“微信运动”
问题：为什么一定要绑定“微信运动”
建议：第一次使用时提醒，下次不要再打扰用户，或者设定每个月提醒一次。


16.一个bug:点赞功能不健全，如下图
没有逗号，我是一个用户，炸酱面是另一个用户

17.一个bug:点赞功能不健全，如下图：
没点赞的前提下，出现了“取消”


图片请见：https://shimo.im/docs/zXNx40kFwgw3ajla

**Comment by alisahuxu** [comment]
18.互动语句没有选错重来的选项
问题：在每天和小白开始第一次互动，有时候，我因为太快选错了，想重来，没有这个按钮。
建议：在互动问询结束后，再问一下：要不要再来一次？

19.症状回顾太长
问题：一个用户随着使用的增加，他的症状是增加的，每次都问一遍，让人没有耐心。
建议方案一：≥3个症状时，合并为表格，让用户勾选，是否有以下几个老症状，如果有，再问是：轻微，中度，严重。
建议方案二：在症状管理界面，可以选择删除已经治愈的症状。

图片请见：https://shimo.im/docs/zXNx40kFwgw3ajla

**Comment by ax003d** [comment]
deadline: 2018-04-01
