### ISSUE TITLE
视频初稿

### ISSUE THREAD

**Issue by fangrongxaing** [sibbay-ai/operating#63]

**Comment by alisahuxu** [comment]
@fangrongxaing 应该有提交物哦。
视频无法上传，截图也发一张。

**Comment by fangrongxaing** [comment]
![1521034866645](https://user-images.githubusercontent.com/33997808/37405762-7331093e-27d0-11e8-9b31-69b40c92fd4e.jpg)
视频过大 无法上传
视频已经发到众和群里

**Comment by fangrongxaing** [comment]
![1521034866645](https://user-images.githubusercontent.com/33997808/37405813-a435bc28-27d0-11e8-9da9-3da6751e2ae1.jpg)

**Comment by fangrongxaing** [comment]
@alisahuxu

**Comment by fangrongxaing** [comment]
![1521035106020](https://user-images.githubusercontent.com/33997808/37406035-2c8e13ae-27d1-11e8-9784-6dfcec805a1a.jpg)
