### ISSUE TITLE
例假管理文案提交

### ISSUE THREAD

**Issue by skytian1** [sibbay-ai/operating#72]
来自https://github.com/sibbay-ai/public/issues/137
例假管理文案设计 @alisahuxu

**Comment by skytian1** [comment]
https://shimo.im/doc/aAXtcd1sqg8WXmFE
https://shimo.im/doc/CWCnelx74loimPQr
https://shimo.im/doc/aIItL6lOgjI79Mgr @alisahuxu

**Comment by skytian1** [comment]
@alisahuxu 申请开发 size:1 Deadline: 2018-03-27

**Comment by alisahuxu** [comment]
好的，因为ICP培训滞后，这个issue提交的有点晚，我上个月已经看过。（说明）

**Comment by alisahuxu** [comment]
deadline:2018-04-15

**Comment by skytian1** [comment]
@fushang318
