### ISSUE TITLE
首次进入互动润色提交

### ISSUE THREAD

**Issue by skytian1** [sibbay-ai/operating#85]
来自https://github.com/sibbay-ai/public/issues/256
@alisahuxu

**Comment by skytian1** [comment]
@alisahuxu申请开发size:0.2

**Comment by skytian1** [comment]
deadline: 2018-04-04

**Comment by alisahuxu** [comment]
deadline:2018-04-15

**Comment by skytian1** [comment]
链接为润色后截图：https://shimo.im/docs/y996m3RGKXYtfGKz

**Comment by skytian1** [comment]
请帮忙review @alisahuxu
