### ISSUE TITLE
完善官网-内容

### ISSUE THREAD

**Issue by alisahuxu** [sibbay-ai/operating#90]
https://shimo.im/docs/uir58Cgyk281hkFn/

**Comment by alisahuxu** [comment]
deadline:2018-04-30

**Comment by alisahuxu** [comment]
申请开发：@fangrongxaing[size:0.3]

**Comment by alisahuxu** [comment]
@fushang318 可以把吴迪老师pimgeek，加入这里吗？

**Comment by fushang318** [comment]
@alisahuxu @pimgeek

**Comment by pimgeek** [comment]
已经确认 @alisahuxu 的开发时间为 0.3，并标 label。

**Comment by fushang318** [comment]
@pimgeek @alisahuxu 
ICP 标签和 size 都是由  commiter 来打，请注意熟知ICP统计规则

**Comment by alisahuxu** [comment]
申请开发：@fushang318[size:0.3]

**Comment by pimgeek** [comment]
我现在不是 Commiter，所以之前的标签操作有误，感谢 @fushang318 的说明。
