### ISSUE TITLE
健康成就--脱发

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/operating#93]
根据运营需求，招募兼职进行脱发主题的文章撰写
**主要工作内容**：文章主题及内容审核、修改
@alisahuxu

**Comment by fazhen** [comment]
deadline:2018-04-15 size:0.1 @alisahuxu

**Comment by fazhen** [comment]
文章已经撰写完成，请运营部同事进行二次审核https://shimo.im/docs/fPqo6vqMcycb5jSA @alisahuxu

**Comment by alisahuxu** [comment]
OK.评论内容有准备好吗？

**Comment by alisahuxu** [comment]
@fazhen

**Comment by fazhen** [comment]
我中午写，下午两点之前给你，时间是否可以 @alisahuxu

**Comment by fushang318** [comment]
updated
