### ISSUE TITLE
地球日画设计

### ISSUE THREAD

**Issue by fangrongxaing** [sibbay-ai/operating#96]
@alisahuxu 申请开发 size:0.5 Deadline: 2018-03-31

**Comment by fangrongxaing** [comment]
@alisahuxu 申请开发 size:0.5 Deadline: 2018-04-31

**Comment by alisahuxu** [comment]
今天已经是30号了。我没明白~

**Comment by fushang318** [comment]
变更 Deadline: 2018-05-15 size:0.5
